version: '3'
services:
  UITester_html_report_develop_container:
   image: node:12
   container_name: 'UITester_html_report_develop_container'
   working_dir: /docker_share_dir
   volumes:
     - ./:/docker_share_dir
   command: bash -c "npm install && npm run server"
   ports:
    # browserSync用ポート
    - 9000:9000
    # browserSync LiveReload用ポート
    - 35729:35729
   environment:
    - DEV_HOST=0.0.0.0
    - DEV_PORT=9000
   tty: true
    
