version: '3'
services:
  UITester_localstack:
    container_name: UITester_localstack
    image: "localstack/localstack"
    ports:
      - "4566:4566"
      - "${PORT_WEB_UI:-8080}:8080"
    environment:
      - PORT_WEB_UI=8080
      - SERVICES=s3,dynamodb,sqs
      - DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data
      - TMPDIR=/private${TMPDIR- }
