version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "UITester"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1cfyy8j6urbqo"
s3_prefix = "UITester"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Env=\"stg\""
