AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# 共通設定
Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        DYNAMODB_TABLE_NAME: !Ref UITesterDynamoDB

Parameters:
  Env: # prod: 本番環境、stg: 検品環境、 local: ローカル開発環境
    Type: String
    AllowedValues:
      - prod
      - stg
      - local
    Default: local

Resources:
  ScreenshotProcessQueingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/projects/ScreenshotProcessQueingFunction/
      Handler: index.lambda_handler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UITesterDynamoDB
        - SQSSendMessagePolicy:
            QueueName:
              !GetAtt ScreenshotProcessSQS.QueueName
      Environment:
        Variables:
          SCREENSHOT_PROCESS_SQS: !Ref ScreenshotProcessSQS
      Events:
        RestPost:
          Type: Api
          Properties:
            RestApiId: !Ref UITesterApi
            Path: /projects/screenshot-queing
            Method: post
  ScreenshotProcessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/projects/ScreenshotProcessFunction/
      Handler: index.lambda_handler
      Runtime: nodejs12.x
      Layers:
        - !Ref PupperteerLayer
      Timeout: 30 # SQSの可視性タイムアウトと揃える
      MemorySize: 1600 # Pupperteerを動かす以上最低必要なメモリ
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UITesterDynamoDB
        - S3CrudPolicy:
            BucketName: !Ref UITesterS3
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref UITesterS3
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ScreenshotProcessSQS.Arn
            BatchSize: 1
  ImageDiffProcessQueingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/projects/ImageDiffProcessQueingFunction/
      Handler: index.lambda_handler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UITesterDynamoDB
        - SQSSendMessagePolicy:
            QueueName:
              !GetAtt ImageDiffProcessSQS.QueueName
      Environment:
        Variables:
          SCREENSHOT_PROCESS_SQS: !Ref ImageDiffProcessSQS
      Events:
        RestPost:
          Type: Api
          Properties:
            RestApiId: !Ref UITesterApi
            Path: /projects/imagediff-queing
            Method: post
  ImageDiffProcessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/projects/ImageDiffProcessFunction/
      Handler: index.lambda_handler
      Runtime: nodejs12.x
      Layers:
        - !Ref NodeResembleJSLayer
      Timeout: 30 # SQSの可視性タイムアウトと揃える
      MemorySize: 1024 # node-resemble-jsを安定動作させるのに必要なメモリ
      Policies:
        - DynamoDBCrudPolicy:
           TableName: !Ref UITesterDynamoDB
        - S3CrudPolicy:
            BucketName: !Ref UITesterS3
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref UITesterS3
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ImageDiffProcessSQS.Arn
            BatchSize: 1

  PupperteerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: 'lambda/layer/pupperteer'
      CompatibleRuntimes:
        - nodejs12.x
    Metadata:
      BuildMethod: nodejs12.x
  NodeResembleJSLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: 'lambda/layer/node-resemble-js'
      CompatibleRuntimes:
        - nodejs12.x
    Metadata:
      BuildMethod: nodejs12.x
            
  UITesterApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Env

  ScreenshotProcessSQS:
    Type: AWS::SQS::Queue
    Properties:
      # 可視性タイムアウト
      VisibilityTimeout: 30
      # メッセージをキューに貯めておく期間
      MessageRetentionPeriod: 86400
      # DLQの設定
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ScreenshotProcessDLQ.Arn
        maxReceiveCount: 1
  ScreenshotProcessDLQ:
    Type: AWS::SQS::Queue
    Properties:
      # 可視性タイムアウト
      VisibilityTimeout: 30
      # メッセージをキューに貯めておく期間
      MessageRetentionPeriod: 86400
  ImageDiffProcessSQS:
    Type: AWS::SQS::Queue
    Properties:
      # 可視性タイムアウト
      VisibilityTimeout: 30
      # メッセージをキューに貯めておく期間
      MessageRetentionPeriod: 86400
      # DLQの設定
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ImageDiffProcessDLQ.Arn
        maxReceiveCount: 1
  ImageDiffProcessDLQ:
    Type: AWS::SQS::Queue
    Properties:
      # 可視性タイムアウト
      VisibilityTimeout: 30
      # メッセージをキューに貯めておく期間
      MessageRetentionPeriod: 86400

  UITesterS3:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${Env}-uitester"
      AccessControl: PublicRead
  UITesterS3Policy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref UITesterS3
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: "Allow"
            Principal: "*"
            Resource: !Sub arn:aws:s3:::${UITesterS3}/*

  UITesterDynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Env}-uitester"
      # 属性の定義
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: ResultSetId
          AttributeType: S
        - AttributeName: ResultName
          AttributeType: S
      # プライマリキープライマリキー、レンジキーの指定
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      # GSIの定義
      GlobalSecondaryIndexes:
        # ユーザ名で検索するためのGSI
        - IndexName: ResultSearchIndex
          KeySchema:
            - AttributeName: ResultSetId
              KeyType: HASH
            - AttributeName: ResultName
              KeyType: RANGE
          # 射影設定
          Projection:
            # 射影する属性の指定
            ProjectionType: ALL
          # GSIのスループットの指定
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
      # スループットの指定
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
  ProjectsQueingApi:
    Description: "Access Command"
    Value: !Sub "curl -X POST -d {} https://${UITesterApi}.execute-api.${AWS::Region}.amazonaws.com/${Env}/projects/screenshot-queing"
  ImageDiffProcessQueingApi:
    Description: "Access Command"
    Value: !Sub "curl -X POST -d {} https://${UITesterApi}.execute-api.${AWS::Region}.amazonaws.com/${Env}/projects/imagediff-queing"
  ScreenshotProcessSQS:
    Description: "ScreenshotProcessSQS PATH"
    Value: !Sub "${ScreenshotProcessSQS}"
  ScreenshotProcessDLQ:
    Description: "ScreenshotProcessDLQ PATH"
    Value: !Sub "${ScreenshotProcessDLQ}"
  ImageDiffProcessSQS:
    Description: "ImageDiffProcessSQS PATH"
    Value: !Sub "${ImageDiffProcessSQS}"
  ImageDiffProcessDLQ:
    Description: "ImageDiffProcessDLQ PATH"
    Value: !Sub "${ImageDiffProcessDLQ}"