AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# 共通設定
Globals:
  Function:
    Timeout: 30
    Layers:
      - !Ref UtilLayer
      - !Ref MyLibLayer
    Environment:
      Variables:
        UITESTER_DYNAMODB_TABLE_NAME: !Ref UITesterDynamoDB
        UITESTER_S3_BUCKET_NAME: !Ref UITesterS3
        TZ: 'Asia/Tokyo'

Parameters:
  Env: # prod: 本番環境、stg: 検品環境、 local: ローカル開発環境
    Type: String
    AllowedValues:
      - prod
      - stg
      - local
    Default: local
  RestApiAuthToken: # RestAPIの認証用トークン(自身で設定)
    Type: String
    Default: hogehoge

Resources:
  # ResultSetの一覧取得
  GetResultSetListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/GetResultSetListFunction/
      Handler: index.lambda_handler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UITesterDynamoDB
      Events:
        RestPost:
          Type: Api
          Properties:
            RestApiId: !Ref UITesterApi
            Path: /result-sets
            Method: get
  # ResultSetの削除
  DeleteResultSetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/DeleteResultSetFunction/
      Handler: index.lambda_handler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UITesterDynamoDB
        - S3CrudPolicy:
            BucketName: !Ref UITesterS3
      Events:
        RestPost:
          Type: Api
          Properties:
            RestApiId: !Ref UITesterApi
            Path: /result-sets/{resultSetId}
            Method: delete
  # Resultの一覧取得
  GetResultListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/GetResultListFunction/
      Handler: index.lambda_handler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UITesterDynamoDB
      Events:
        RestPost:
          Type: Api
          Properties:
            RestApiId: !Ref UITesterApi
            Path: /result-sets/{resultSetId}/results
            Method: get
  # ResultSetのレポート取得処理
  GetResultSetReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/GetResultSetReportFunction/
      Handler: index.lambda_handler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UITesterDynamoDB
      Events:
        RestPost:
          Type: Api
          Properties:
            RestApiId: !Ref UITesterApi
            Path: /result-sets/{resultSetId}/report/{reportType}
            Method: get
  # スクリーンショット取得処理のキューイング処理
  ScreenshotProcessQueingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/ScreenshotProcessQueingFunction/
      Handler: index.lambda_handler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UITesterDynamoDB
        - SQSSendMessagePolicy:
            QueueName:
              !GetAtt ScreenshotProcessSQS.QueueName
      Environment:
        Variables:
          SCREENSHOT_PROCESS_SQS: !Ref ScreenshotProcessSQS
      Events:
        RestPost:
          Type: Api
          Properties:
            RestApiId: !Ref UITesterApi
            Path: /result-sets/screenshot-queing
            Method: post
  # スクリーンショット取得処理
  ScreenshotProcessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/ScreenshotProcessFunction/
      Handler: index.lambda_handler
      Runtime: nodejs12.x
      Layers:
        - !Ref PuppeteerLayer
      Timeout: 30 # SQSの可視性タイムアウトと揃える
      MemorySize: 1600 # Puppeteerを動かす以上最低必要なメモリ
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UITesterDynamoDB
        - S3CrudPolicy:
            BucketName: !Ref UITesterS3
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ScreenshotProcessSQS.Arn
            BatchSize: 1
  # 画像差分取得処理のキューイング処理
  ImageDiffProcessQueingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/ImageDiffProcessQueingFunction/
      Handler: index.lambda_handler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UITesterDynamoDB
        - SQSSendMessagePolicy:
            QueueName:
              !GetAtt ImageDiffProcessSQS.QueueName
      Environment:
        Variables:
          SCREENSHOT_PROCESS_SQS: !Ref ImageDiffProcessSQS
      Events:
        RestPost:
          Type: Api
          Properties:
            RestApiId: !Ref UITesterApi
            Path: /result-sets/imagediff-queing
            Method: post
  # 画像差分取得処理
  ImageDiffProcessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/ImageDiffProcessFunction/
      Handler: index.lambda_handler
      Runtime: nodejs12.x
      Layers:
        - !Ref NodeResembleJSLayer
      Timeout: 30 # SQSの可視性タイムアウトと揃える
      MemorySize: 1024 # node-resemble-jsを安定動作させるのに必要なメモリ
      Policies:
        - DynamoDBCrudPolicy:
           TableName: !Ref UITesterDynamoDB
        - S3CrudPolicy:
            BucketName: !Ref UITesterS3
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ImageDiffProcessSQS.Arn
            BatchSize: 1
  # RESTAPIのLambdaAuthorizer
  RestApiAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/RestApiAuthFunction/
      Handler: index.lambda_handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          AUTH_TOKEN: !Ref RestApiAuthToken

  # Puppeteer(chrome-aws-lambda)の関連ライブラリのレイヤー
  PuppeteerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: 'lambda/layer/puppeteer'
      CompatibleRuntimes:
        - nodejs12.x
    Metadata:
      BuildMethod: nodejs12.x
  # NodeResembleJS(画像比較ライブラリ)のレイヤー
  NodeResembleJSLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: 'lambda/layer/node-resemble-js'
      CompatibleRuntimes:
        - nodejs12.x
    Metadata:
      BuildMethod: nodejs12.x
  # 汎用的なライブラリのレイヤー
  UtilLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: 'lambda/layer/util'
      CompatibleRuntimes:
        - nodejs12.x
    Metadata:
      BuildMethod: nodejs12.x
  # 自前で実装した共通ライブラリのレイヤー
  MyLibLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: 'lambda/layer/my-lib'
      CompatibleRuntimes:
        - nodejs12.x
    Metadata:
      BuildMethod: nodejs12.x
            
  UITesterApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Env
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'*'"
      Auth:
        AddDefaultAuthorizerToCorsPreflight: false
        DefaultAuthorizer: MyLambdaCustomAuthorizer
        Authorizers:
          MyLambdaCustomAuthorizer:
            FunctionPayloadType: REQUEST
            FunctionArn: !GetAtt RestApiAuthFunction.Arn
            Identity:
              QueryStrings:
                - authToken

  # スクリーンショット取得処理のキュー
  ScreenshotProcessSQS:
    Type: AWS::SQS::Queue
    Properties:
      # 可視性タイムアウト
      VisibilityTimeout: 30
      # メッセージをキューに貯めておく期間
      MessageRetentionPeriod: 86400
      # DLQの設定
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ScreenshotProcessDLQ.Arn
        maxReceiveCount: 1
  # スクリーンショット取得処理のデッドレターキュー
  ScreenshotProcessDLQ:
    Type: AWS::SQS::Queue
    Properties:
      # 可視性タイムアウト
      VisibilityTimeout: 30
      # メッセージをキューに貯めておく期間
      MessageRetentionPeriod: 86400
  # 画像差分比較処理のキュー
  ImageDiffProcessSQS:
    Type: AWS::SQS::Queue
    Properties:
      # 可視性タイムアウト
      VisibilityTimeout: 30
      # メッセージをキューに貯めておく期間
      MessageRetentionPeriod: 86400
      # DLQの設定
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ImageDiffProcessDLQ.Arn
        maxReceiveCount: 1
  # 画像差分比較処理のデッドレターキュー
  ImageDiffProcessDLQ:
    Type: AWS::SQS::Queue
    Properties:
      # 可視性タイムアウト
      VisibilityTimeout: 30
      # メッセージをキューに貯めておく期間
      MessageRetentionPeriod: 86400

  # 本アプリで利用するS3バケット
  UITesterS3:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${Env}-uitester"
      AccessControl: PublicRead
  UITesterS3Policy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref UITesterS3
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: "Allow"
            Principal: "*"
            Resource: !Sub arn:aws:s3:::${UITesterS3}/*

  # 本アプリで利用するDynamoDB
  UITesterDynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Env}-uitester"
      # 属性の定義
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: ResultSetId
          AttributeType: S
        - AttributeName: ResultName
          AttributeType: S
      # プライマリキープライマリキー、レンジキーの指定
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      # GSIの定義
      GlobalSecondaryIndexes:
        # ユーザ名で検索するためのGSI
        - IndexName: ResultSearchIndex
          KeySchema:
            - AttributeName: ResultSetId
              KeyType: HASH
            - AttributeName: ResultName
              KeyType: RANGE
          # 射影設定
          Projection:
            # 射影する属性の指定
            ProjectionType: ALL
          # GSIのスループットの指定
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
      # スループットの指定
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
  GetResultSetListFunction:
    Description: "Access Command"
    Value: !Sub "curl https://${UITesterApi}.execute-api.${AWS::Region}.amazonaws.com/${Env}/result-sets/?authToken=${RestApiAuthToken}"
  DeleteResultSetFunction:
    Description: "Access Command"
    Value: !Sub "curl -X DELETE https://${UITesterApi}.execute-api.${AWS::Region}.amazonaws.com/${Env}/result-sets/{resultSetId}/?authToken=${RestApiAuthToken}"
  GetResultListFunction:
    Description: "Access Command"
    Value: !Sub "curl https://${UITesterApi}.execute-api.${AWS::Region}.amazonaws.com/${Env}/result-sets/{resultSetId}/results/?authToken=${RestApiAuthToken}"
  GetResultSetReportFunction:
    Description: "Access Command"
    Value: !Sub "curl https://${UITesterApi}.execute-api.${AWS::Region}.amazonaws.com/${Env}/result-sets/{resultSetId}/report/{reportType = (html)}/?authToken=${RestApiAuthToken}"
  ScreenshotProcessQueingFunction:
    Description: "Access Command"
    Value: !Sub "curl -X POST -d {} https://${UITesterApi}.execute-api.${AWS::Region}.amazonaws.com/${Env}/result-sets/screenshot-queing/?authToken=${RestApiAuthToken}"
  ImageDiffProcessQueingApi:
    Description: "Access Command"
    Value: !Sub "curl -X POST -d {} https://${UITesterApi}.execute-api.${AWS::Region}.amazonaws.com/${Env}/result-sets/imagediff-queing/?authToken=${RestApiAuthToken}"
  ScreenshotProcessSQS:
    Description: "ScreenshotProcessSQS PATH"
    Value: !Sub "${ScreenshotProcessSQS}"
  ScreenshotProcessDLQ:
    Description: "ScreenshotProcessDLQ PATH"
    Value: !Sub "${ScreenshotProcessDLQ}"
  ImageDiffProcessSQS:
    Description: "ImageDiffProcessSQS PATH"
    Value: !Sub "${ImageDiffProcessSQS}"
  ImageDiffProcessDLQ:
    Description: "ImageDiffProcessDLQ PATH"
    Value: !Sub "${ImageDiffProcessDLQ}"