AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Parameters:
  Env: # prod: 本番環境、stg: 検品環境、 local: ローカル開発環境
    Type: String
    AllowedValues:
      - prod
      - stg
      - local
    Default: local

Resources:
  ProjectsQueingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/projects/
      Handler: queing.lambda_handler
      Runtime: python3.8
      Events:
        RestPost:
          Type: Api
          Properties:
            RestApiId: !Ref UITesterApi
            Path: /projects/queing
            Method: post
  UITesterApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Env

Outputs:
  ProjectsQueingApi:
    Description: "Access Command"
    Value: !Sub "curl -X POST -d {} https://${UITesterApi}.execute-api.${AWS::Region}.amazonaws.com/${Env}/projects/queing/"