AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Parameters:
  Env: # prod: 本番環境、stg: 検品環境、 local: ローカル開発環境
    Type: String
    AllowedValues:
      - prod
      - stg
      - local
    Default: local

Resources:
  ProjectsQueingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/projects/
      Handler: queing.lambda_handler
      Runtime: nodejs12.x
      Policies:
        - SQSSendMessagePolicy:
            QueueName:
              !GetAtt ScreenshotProcessSQS.QueueName
      Environment:
        Variables:
          SCREENSHOT_PROCESS_SQS: !Ref ScreenshotProcessSQS
      Events:
        RestPost:
          Type: Api
          Properties:
            RestApiId: !Ref UITesterApi
            Path: /projects/queing
            Method: post
  ScreenshotProcessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/projects/
      Handler: pulling.lambda_handler
      Runtime: nodejs12.x
      Layers:
        - !Ref PupperteerLayer
      Timeout: 30 # SQSの可視性タイムアウトと揃える
      MemorySize: 1600 # Pupperteerを動かす以上最低必要なメモリ
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref UITesterS3
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref UITesterS3
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ScreenshotProcessSQS.Arn
            BatchSize: 1
  ImageDiffProcessQueingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/projects/
      Handler: imagediff-queing.lambda_handler
      Runtime: nodejs12.x
      Policies:
        - SQSSendMessagePolicy:
            QueueName:
              !GetAtt ImageDiffProcessSQS.QueueName
      Environment:
        Variables:
          SCREENSHOT_PROCESS_SQS: !Ref ImageDiffProcessSQS
      Events:
        RestPost:
          Type: Api
          Properties:
            RestApiId: !Ref UITesterApi
            Path: /projects/imagediff-queing
            Method: post
  ImageDiffProcessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/projects/
      Handler: imagediff.lambda_handler
      Runtime: nodejs12.x
      Layers:
        - !Ref NodeResembleJSLayer
      Timeout: 30 # SQSの可視性タイムアウトと揃える
      MemorySize: 1024 # node-resemble-jsを安定動作させるのに必要なメモリ
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref UITesterS3
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref UITesterS3
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ImageDiffProcessSQS.Arn
            BatchSize: 1

  PupperteerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: 'lambda/layer/pupperteer'
      CompatibleRuntimes:
        - nodejs12.x
    Metadata:
      BuildMethod: nodejs12.x
  NodeResembleJSLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: 'lambda/layer/node-resemble-js'
      CompatibleRuntimes:
        - nodejs12.x
    Metadata:
      BuildMethod: nodejs12.x
            
  UITesterApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Env

  ScreenshotProcessSQS:
    Type: AWS::SQS::Queue
    Properties:
      # 可視性タイムアウト
      VisibilityTimeout: 30
      # メッセージをキューに貯めておく期間
      MessageRetentionPeriod: 86400
      # DLQの設定
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ScreenshotProcessDLQ.Arn
        maxReceiveCount: 1
  ScreenshotProcessDLQ:
    Type: AWS::SQS::Queue
    Properties:
      # 可視性タイムアウト
      VisibilityTimeout: 30
      # メッセージをキューに貯めておく期間
      MessageRetentionPeriod: 86400
  ImageDiffProcessSQS:
    Type: AWS::SQS::Queue
    Properties:
      # 可視性タイムアウト
      VisibilityTimeout: 30
      # メッセージをキューに貯めておく期間
      MessageRetentionPeriod: 86400
      # DLQの設定
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ImageDiffProcessDLQ.Arn
        maxReceiveCount: 1
  ImageDiffProcessDLQ:
    Type: AWS::SQS::Queue
    Properties:
      # 可視性タイムアウト
      VisibilityTimeout: 30
      # メッセージをキューに貯めておく期間
      MessageRetentionPeriod: 86400

  UITesterS3:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${Env}-uitester"
      AccessControl: PublicRead
  UITesterS3Policy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref UITesterS3
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: "Allow"
            Principal: "*"
            Resource: !Sub arn:aws:s3:::${UITesterS3}/*

Outputs:
  ProjectsQueingApi:
    Description: "Access Command"
    Value: !Sub "curl -X POST -d {} https://${UITesterApi}.execute-api.${AWS::Region}.amazonaws.com/${Env}/projects/queing/"
  ImageDiffProcessQueingApi:
    Description: "Access Command"
    Value: !Sub "curl -X POST -d {} https://${UITesterApi}.execute-api.${AWS::Region}.amazonaws.com/${Env}/projects/imagediff-queing"
  ScreenshotProcessSQS:
    Description: "ScreenshotProcessSQS PATH"
    Value: !Sub "${ScreenshotProcessSQS}"
  ScreenshotProcessDLQ:
    Description: "ScreenshotProcessDLQ PATH"
    Value: !Sub "${ScreenshotProcessDLQ}"
  ImageDiffProcessSQS:
    Description: "ImageDiffProcessSQS PATH"
    Value: !Sub "${ImageDiffProcessSQS}"
  ImageDiffProcessDLQ:
    Description: "ImageDiffProcessDLQ PATH"
    Value: !Sub "${ImageDiffProcessDLQ}"